<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Invoice.Data\Invoice.Data.csproj" />
    <ProjectReference Include="..\Invoice.DTOs\Invoice.DTOs.csproj" />
    <ProjectReference Include="..\Invoice.Model\Invoice.Model.csproj" />
  </ItemGroup>

</Project>
