<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Invoice.DAL\Invoice.DAL.csproj" />
    <ProjectReference Include="..\Invoice.Data\Invoice.Data.csproj" />
    <ProjectReference Include="..\Invoice.DTOs\Invoice.DTOs.csproj" />
    <ProjectReference Include="..\Invoice.Model\Invoice.Model.csproj" />
  </ItemGroup>

</Project>
